import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Store,
  Users,
  Wallet,
  Megaphone,
  FileText,
  Headset,
  UserCog,
  BarChart3,
  Sparkles,
  Wand2,
  FlaskConical,
  Film,
  Gem,
  Plug,
  Bot,
  ListChecks,
  Gauge,
  ServerCog,
  BadgePercent,
} from "lucide-react";

/* Full information architecture. Every module is reachable from the sidebar;
   modules without a real page yet render <ComingSoon />. */
const navConfig = [
  { type: "link", id: "home", href: "/", label: "داشبورد", icon: LayoutDashboard, exact: true },
  {
    type: "group",
    id: "orders",
    label: "سفارشات",
    icon: ShoppingCart,
    items: [
      { href: "/orders", label: "لیست سفارشات", exact: true },
      { href: "/orders/analytics", label: "آنالیتیکس فروش" },
      { href: "/orders/abandoned", label: "سفارشات رها‌شده" },
    ],
  },
  {
    type: "group",
    id: "catalog",
    label: "کاتالوگ محصولات",
    icon: Package,
    items: [
      { href: "/products", label: "همه محصولات", exact: true },
      { href: "/products/analytics", label: "آمار محصولات" },
      { href: "/products/new", label: "افزودن محصول" },
      { href: "/products/categories", label: "دسته‌بندی‌ها" },
      { href: "/products/brands", label: "برندها" },
      { href: "/products/types", label: "نوع محصول" },
      { href: "/products/dynamic-price", label: "قیمت‌گذاری پویا (درصدی)" },
      { href: "/products/labels", label: "برچسب‌ها" },
      { href: "/products/reviews", label: "نقد و بررسی" },
    ],
  },
  {
    type: "group",
    id: "vendors",
    label: "فروشندگان",
    icon: Store,
    items: [
      { href: "/vendors", label: "همه فروشندگان", exact: true },
      { href: "/vendors/products", label: "محصولات فروشندگان" },
    ],
  },
  {
    type: "group",
    id: "crm",
    label: "مشتریان و CRM",
    icon: Users,
    items: [
      { href: "/customers", label: "لیست مشتریان", exact: true },
      { href: "/crm", label: "سگمنت، کمپین و اتوماسیون" },
    ],
  },
  {
    type: "group",
    id: "analytics",
    label: "آنالیتیکس",
    icon: BarChart3,
    items: [
      { href: "/analytics", label: "نمای کلی", exact: true },
      { href: "/analytics/sessions", label: "جلسات بازدیدکنندگان" },
    ],
  },
  {
    type: "group",
    id: "financial",
    label: "امور مالی",
    icon: Wallet,
    items: [
      { href: "/financial", label: "نمای کلی مالی", exact: true },
      { href: "/financial/transactions", label: "تراکنش‌های مشتریان" },
      { href: "/financial/vendors", label: "تسویه فروشندگان" },
      { href: "/financial/staff", label: "امور مالی همکاران" },
    ],
  },
  {
    type: "group",
    id: "marketing",
    label: "بازاریابی",
    icon: Megaphone,
    items: [
      { href: "/marketing/discounts", label: "کدهای تخفیف", exact: true },
      { href: "/marketing/campaigns", label: "کمپین‌ها" },
      { href: "/marketing/modals", label: "مودال‌ساز" },
    ],
  },
  {
    type: "group",
    id: "content",
    label: "محتوا و صفحات",
    icon: FileText,
    items: [
      { href: "/content/blog", label: "بلاگ", exact: true },
      { href: "/content/blog/categories", label: "دسته‌بندی‌های بلاگ" },
      { href: "/content/blog/tags", label: "تگ‌های بلاگ" },
      { href: "/content/blog/author-profile", label: "پروفایل نویسندگی" },
      { href: "/content/menu-builder", label: "منوساز" },
      { href: "/content/page-builder", label: "صفحه‌ساز" },
      { href: "/content/homepage", label: "چیدمان صفحه اصلی" },
      { href: "/content/faq", label: "سوالات متداول" },
      { href: "/content/info-pages", label: "صفحات اطلاعات (درباره ما، حریم خصوصی…)" },
      { href: "/settings/top-banner", label: "بنر بالای هدر" },
      { href: "/settings/header-quick-tabs", label: "تب‌های دسترسی سریع هدر" },
      { href: "/settings/product-page", label: "ارسال رایگان و بنرهای صفحه محصول" },
      { href: "/settings/footer", label: "تنظیمات فوتر" },
      { href: "/settings/whatsapp-widget", label: "ویجت واتس‌اپ" },
      { href: "/settings/product-card", label: "طراحی کارت محصول" },
      { href: "/settings/branding", label: "لوگو و برندینگ" },
      { href: "/settings/images", label: "بهینه‌سازی تصاویر" },
      { href: "/settings/taxonomy-seo", label: "تنظیمات سئوی دسته/برند/برچسب" },
    ],
  },
  { type: "link", id: "seo", href: "/seo", label: "مرکز سئو", icon: Gauge },
  {
    type: "group",
    id: "pricing-intelligence",
    label: "قیمت‌گذاری هوشمند",
    icon: BadgePercent,
    items: [
      { href: "/pricing-intelligence", label: "داشبورد", exact: true },
      { href: "/pricing-intelligence/market", label: "مقایسه بازار" },
      { href: "/pricing-intelligence/products", label: "جدول محصولات" },
      { href: "/pricing-intelligence/simulate", label: "شبیه‌سازی" },
      { href: "/pricing-intelligence/settings", label: "تنظیمات موتور" },
      { href: "/pricing-intelligence/audit", label: "تاریخچه و جاب‌ها" },
    ],
  },
  { type: "link", id: "system-health", href: "/system-health", label: "وضعیت سیستم", icon: ServerCog },
  { type: "link", id: "feed", href: "/feed", label: "فید", icon: Film },
  { type: "link", id: "loyalty", href: "/loyalty", label: "باشگاه مشتریان", icon: Gem },
  { type: "link", id: "mcp-integration", href: "/integrations/mcp", label: "اتصال Claude (MCP)", icon: Plug },
  { type: "link", id: "crawler", href: "/integrations/crawler", label: "کراولر محصولات", icon: Bot },
  {
    type: "group",
    id: "beauty-profile",
    label: "پروفایل زیبایی",
    icon: Wand2,
    items: [
      { href: "/beauty-profile/settings", label: "فعال‌سازی و تنظیمات", exact: true },
      { href: "/beauty-profile/questions", label: "سوالات" },
      { href: "/beauty-profile/responses", label: "پاسخ‌های مشتریان" },
    ],
  },
  {
    type: "group",
    id: "beauty-hub",
    label: "دانشنامه زیبایی",
    icon: FlaskConical,
    items: [
      { href: "/beauty/dashboard", label: "نمای کلی", exact: true },
      { href: "/beauty/skin-types", label: "انواع پوست" },
      { href: "/beauty/skin-concerns", label: "دغدغه‌های پوستی" },
      { href: "/beauty/ingredients", label: "ترکیبات" },
      { href: "/beauty/routines", label: "قالب‌های روتین" },
      { href: "/beauty/content-guide", label: "راهنمای تولید محتوا" },
    ],
  },
  {
    type: "group",
    id: "routine-builder",
    label: "روتین‌ساز",
    icon: ListChecks,
    items: [
      { href: "/routine-builder/settings", label: "فعال‌سازی و تنظیمات", exact: true },
      { href: "/beauty/routines", label: "قالب‌های روتین" },
    ],
  },
  {
    type: "group",
    id: "ai-assistant",
    label: "دستیار هوشمند",
    icon: Sparkles,
    items: [
      { href: "/ai", label: "نمای کلی", exact: true },
      { href: "/ai/conversations", label: "مکالمات" },
      { href: "/ai/settings", label: "تنظیمات" },
    ],
  },
  {
    type: "group",
    id: "support",
    label: "پشتیبانی",
    icon: Headset,
    items: [
      { href: "/support/live-chat", label: "چت‌های زنده", exact: true },
      { href: "/support/tickets", label: "تیکت‌ها", exact: true },
      { href: "/support/comments", label: "نظرات محصولات" },
      { href: "/support/chat-settings", label: "تنظیمات چت زنده (روشن/خاموش و زمان‌بندی)" },
    ],
  },
  { type: "link", id: "staff", href: "/staff", label: "کارکنان", icon: UserCog },
];

export default navConfig;
